# pytorch_lightning==2.4.0
seed_everything: 0
trainer:
  check_val_every_n_epoch: 1
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: test
      name: MNIST
      offline: true
      log_model: false # if offline true cannot be true as well
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 3
        mode: min
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: 'epoch'
# optimizer:
#   class_path: torch.optim.SGD
#   init_args:
#     lr: 0.04
lr_scheduler:
  class_path: pytorch_lightning.cli.ReduceLROnPlateau
  init_args:
    monitor: train_loss
    mode: min
    patience: 5
model:
  class_path: models.lightning.LitAutoEncoder
data:
  class_path: datasets.mnist_lightning.MNISTDataModule
  init_args:
    data_dir: null
    batch_size: 8192
    num_workers: 16
