model:
  class_path: models.lightning.GraphLitModel
  init_args:
    name: GPS_B${data.init_args.batch_size}_L2_H64_A1_[[features]]
    module:
      class_path: torch_geometric.nn.Sequential
      init_args:
        input_args: x, edge_index, batch
        modules:
          - - class_path: torch_geometric.nn.conv.GPSConv
              init_args:
                channels: 1
                heads: 1
                dropout: 0.2
                act: relu
            - x, edge_index, batch -> x
          - - class_path: models.utils.my_global_mean_pool
            - x, batch -> x
    learning_rate: 1e-3
    loss_fn:
      class_path: torch.nn.CrossEntropyLoss
