trainer:
  check_val_every_n_epoch: 1
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: sulcalgraphs_left
      group: ${model.init_args.name}
      offline: false
      log_model: all # if offline true cannot be true as well
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
    # - class_path: pytorch_lightning.callbacks.EarlyStopping
    #   init_args:
    #     monitor: val/loss
    #     patience: 100
    #     mode: min
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        mode: min
        save_last: true
        dirpath: [[temp_dir]]
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    # - class_path: pytorch_lightning.callbacks.BatchSizeFinder
  max_epochs: 250
  min_epochs: 100
  benchmark: true
