data:
  class_path: datasets.utils.MyLightningDataset
  init_args:
    train_dataset:
      class_path: datasets.sulcalgraphs.SulcalGraphs
      init_args:
        root: [[temp_dir]]
        csv_path: data/sulcalgraphs.csv
        node_attrs:
          - vertex_index
        split: train
    val_dataset:
      class_path: datasets.sulcalgraphs.SulcalGraphs
      init_args:
        root: [[temp_dir]]
        csv_path: data/sulcalgraphs.csv
        node_attrs:
          - vertex_index
        split: val
    test_dataset:
      class_path: datasets.sulcalgraphs.SulcalGraphs
      init_args:
        root: [[temp_dir]]
        csv_path: data/sulcalgraphs.csv
        node_attrs:
          - vertex_index
        split: test
    num_workers: 64
    batch_size: 64
    pin_memory: true
